[package]
name = "random-sensor-service"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.48", features = ["derive"] }
signal-hook = "0.3.18"

[dev-dependencies]
tempfile = "3.23.0"
